# action.yml
name: 'Shamik Action'
description: 'Greet someone and record the time'
inputs:
  studio-cli-command:  
    description: 'Command to execute'
    required: true
outputs:
  message: 
    description: 'Command output'
runs:
  using: 'docker'
  image: 'Dockerfile'
 
