# action.yml
name: 'Shamik Action'
description: 'Greet someone and record the time'
inputs:
  studio-cli-command:  # id of input
    description: 'Command to execute'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'Command output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.studio-cli-command }}

